version: '3.8'

services:
  postgres:
    container_name: inBev
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: inBev
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: saulotm90@outlook.com
      PGADMIN_DEFAULT_PASSWORD: 123456

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
